[tool.poetry]
name = "animated-fiesta"
description = "my collection"
version = "0.1.0"
authors = ["foo"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
